概要：熟悉tensorflow的基本操作。

1.张量。

In [10]:
import tensorflow as tf

a = 1.2
aa = tf.constant(1.2)

type(a), type(aa), tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

In [11]:
x = tf.constant([1.2, 4])
x

<tf.Tensor: id=9, shape=(2,), dtype=float32, numpy=array([1.2, 4. ], dtype=float32)>

In [12]:
x.numpy()

array([1.2, 4. ], dtype=float32)

In [13]:
x.dtype

tf.float32

In [14]:
x.shape

TensorShape([2])

定义向量：

In [15]:
a = tf.constant([1.2])
a

<tf.Tensor: id=12, shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>

In [16]:
a.shape

TensorShape([1])

定义三维张量：

In [17]:
a = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])

In [18]:
a

<tf.Tensor: id=14, shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>

创建字符串：

In [23]:
a = tf.constant('i am a chinese.')
a

<tf.Tensor: id=90, shape=(), dtype=string, numpy=b'i am a chinese.'>

字符串操作：

In [24]:
tf.strings.upper(a)

<tf.Tensor: id=92, shape=(), dtype=string, numpy=b'I AM A CHINESE.'>

布尔类型：

In [28]:
a = tf.constant(True)
a

<tf.Tensor: id=96, shape=(), dtype=bool, numpy=True>

布尔向量：

In [29]:
a = tf.constant([True, False])
a

<tf.Tensor: id=98, shape=(2,), dtype=bool, numpy=array([ True, False])>

数值精度：

In [32]:
tf.constant(123456789, dtype=tf.int16)

<tf.Tensor: id=104, shape=(), dtype=int16, numpy=-13035>

In [34]:
tf.constant(123456789, dtype=tf.int32)

<tf.Tensor: id=108, shape=(), dtype=int32, numpy=123456789>

PI的精度：

In [36]:
import numpy as np

np.pi

3.141592653589793

In [39]:
tf.constant(np.pi, dtype=tf.float32)

<tf.Tensor: id=114, shape=(), dtype=float32, numpy=3.1415927>

In [40]:
tf.constant(np.pi, dtype=tf.float64)

<tf.Tensor: id=116, shape=(), dtype=float64, numpy=3.141592653589793>

类型转换：

In [42]:
a = tf.constant(np.pi, dtype=tf.float16)
a

<tf.Tensor: id=119, shape=(), dtype=float16, numpy=3.14>

In [46]:
tf.cast(a, tf.float32)

<tf.Tensor: id=127, shape=(), dtype=float32, numpy=3.140625>

布尔类型和整数类型的转换：

In [47]:
a = tf.constant([True, False])
tf.cast(a, tf.int8)

<tf.Tensor: id=130, shape=(2,), dtype=int8, numpy=array([1, 0], dtype=int8)>

非0数字都是True:

In [49]:
tf.cast([1, 2, -1 , 0], tf.bool)

<tf.Tensor: id=418, shape=(4,), dtype=bool, numpy=array([ True,  True,  True, False])>

待优化张量：

In [56]:
a = tf.constant([1,2,3,4])
aa = tf.Variable(a)
aa.name, aa.trainable

('Variable:0', True)

2. 创建张量。

从numpy array中创建：

In [60]:
tf.convert_to_tensor(np.array([[1,2], [3.,4]]))

<tf.Tensor: id=468, shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

创建全0，1标量：

In [62]:
tf.zeros([]),tf.ones([])

(<tf.Tensor: id=882, shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: id=883, shape=(), dtype=float32, numpy=1.0>)

创建全0，1向量：

In [67]:
tf.zeros([2]),tf.ones([3])

(<tf.Tensor: id=1380, shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Tensor: id=1383, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>)

In [ ]:
创建全0，1矩阵：

In [71]:
tf.zeros([2,3]),tf.ones([3,3])

(<tf.Tensor: id=2544, shape=(2, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: id=2547, shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>)

创建和某个张量shape一致的全0，1张量：

In [77]:
tf.zeros_like(a)

<tf.Tensor: id=3209, shape=(4,), dtype=int32, numpy=array([0, 0, 0, 0])>