概要：熟悉tensorflow的基本操作。

1.张量。

In [50]:
import tensorflow as tf

a = 1.2
aa = tf.constant(1.2)

type(a), type(aa), tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

In [2]:
x = tf.constant([1.2, 4])
x

<tf.Tensor: id=1, shape=(2,), dtype=float32, numpy=array([1.2, 4. ], dtype=float32)>

In [3]:
x.numpy()

array([1.2, 4. ], dtype=float32)

In [4]:
x.dtype

tf.float32

In [5]:
x.shape

TensorShape([2])

定义向量：

In [6]:
a = tf.constant([1.2])
a

<tf.Tensor: id=4, shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>

In [7]:
a.shape

TensorShape([1])

定义三维张量：

In [8]:
a = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])

In [9]:
a

<tf.Tensor: id=6, shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>

创建字符串：

In [10]:
a = tf.constant('i am a chinese.')
a

<tf.Tensor: id=8, shape=(), dtype=string, numpy=b'i am a chinese.'>

字符串操作：

In [11]:
tf.strings.upper(a)

<tf.Tensor: id=10, shape=(), dtype=string, numpy=b'I AM A CHINESE.'>

布尔类型：

In [12]:
a = tf.constant(True)
a

<tf.Tensor: id=12, shape=(), dtype=bool, numpy=True>

布尔向量：

In [13]:
a = tf.constant([True, False])
a

<tf.Tensor: id=14, shape=(2,), dtype=bool, numpy=array([ True, False])>

数值精度：

In [14]:
tf.constant(123456789, dtype=tf.int16)

<tf.Tensor: id=16, shape=(), dtype=int16, numpy=-13035>

In [15]:
tf.constant(123456789, dtype=tf.int32)

<tf.Tensor: id=18, shape=(), dtype=int32, numpy=123456789>

PI的精度：

In [16]:
import numpy as np

np.pi

3.141592653589793

In [17]:
tf.constant(np.pi, dtype=tf.float32)

<tf.Tensor: id=20, shape=(), dtype=float32, numpy=3.1415927>

In [18]:
tf.constant(np.pi, dtype=tf.float64)

<tf.Tensor: id=22, shape=(), dtype=float64, numpy=3.141592653589793>

类型转换：

In [19]:
a = tf.constant(np.pi, dtype=tf.float16)
a

<tf.Tensor: id=24, shape=(), dtype=float16, numpy=3.14>

In [20]:
tf.cast(a, tf.float32)

<tf.Tensor: id=26, shape=(), dtype=float32, numpy=3.140625>

布尔类型和整数类型的转换：

In [21]:
a = tf.constant([True, False])
tf.cast(a, tf.int8)

<tf.Tensor: id=29, shape=(2,), dtype=int8, numpy=array([1, 0], dtype=int8)>

非0数字都是True:

In [22]:
tf.cast([1, 2, -1 , 0], tf.bool)

<tf.Tensor: id=32, shape=(4,), dtype=bool, numpy=array([ True,  True,  True, False])>

待优化张量：

In [23]:
a = tf.constant([1,2,3,4])
aa = tf.Variable(a)
aa.name, aa.trainable

('Variable:0', True)

2. 创建张量。

从numpy array中创建：

In [24]:
tf.convert_to_tensor(np.array([[1,2], [3.,4]]))

<tf.Tensor: id=42, shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

创建全0，1标量：

In [25]:
tf.zeros([]),tf.ones([])

(<tf.Tensor: id=44, shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: id=45, shape=(), dtype=float32, numpy=1.0>)

创建全0，1向量：

In [26]:
tf.zeros([2]),tf.ones([3])

(<tf.Tensor: id=50, shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Tensor: id=53, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>)

创建全0，1矩阵：

In [28]:
tf.zeros([2,3]),tf.ones([3,3])

(<tf.Tensor: id=58, shape=(2, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: id=61, shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>)

创建和某个张量shape一致的全0，1张量：

In [29]:
tf.zeros_like(a)

<tf.Tensor: id=64, shape=(4,), dtype=int32, numpy=array([0, 0, 0, 0])>

创建自定义数值的张量：

In [35]:
tf.fill(tf.shape(a), -1)

<tf.Tensor: id=347, shape=(4,), dtype=int32, numpy=array([-1, -1, -1, -1])>

In [40]:
tf.fill([], -2)

<tf.Tensor: id=653, shape=(), dtype=int32, numpy=-2>

In [41]:
tf.fill([2,2], -1)

<tf.Tensor: id=657, shape=(2, 2), dtype=int32, numpy=
array([[-1, -1],
       [-1, -1]])>

创建正太分布的张量：

In [45]:
tf.random.normal([3,3], mean=0, stddev=1)

<tf.Tensor: id=685, shape=(3, 3), dtype=float32, numpy=
array([[-1.4284813 ,  1.2248629 , -0.43903226],
       [ 2.057181  ,  1.061179  , -0.02747896],
       [ 0.8619253 , -1.2881715 ,  1.2134948 ]], dtype=float32)>

创建均匀分布的张量：

In [46]:
tf.random.uniform([2,2], minval=0, maxval=1, dtype=tf.float32)

<tf.Tensor: id=693, shape=(2, 2), dtype=float32, numpy=
array([[0.5637926 , 0.54485226],
       [0.02157629, 0.54366887]], dtype=float32)>

创建序列;

In [48]:
tf.range(10)

<tf.Tensor: id=698, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [49]:
tf.range(0, 10, delta=1)

<tf.Tensor: id=1515, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

3.张量的典型应用。