概要：熟悉tensorflow的基本操作。

1.张量。

In [91]:
import tensorflow as tf
from    tensorflow import keras
from    tensorflow.keras import layers, optimizers, datasets

a = 1.2
aa = tf.constant(1.2)

type(a), type(aa), tf.is_tensor(aa)

(float, tensorflow.python.framework.ops.EagerTensor, True)

In [2]:
x = tf.constant([1.2, 4])
x

<tf.Tensor: id=1, shape=(2,), dtype=float32, numpy=array([1.2, 4. ], dtype=float32)>

In [3]:
x.numpy()

array([1.2, 4. ], dtype=float32)

In [4]:
x.dtype

tf.float32

In [5]:
x.shape

TensorShape([2])

定义向量：

In [6]:
a = tf.constant([1.2])
a

<tf.Tensor: id=4, shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>

In [7]:
a.shape

TensorShape([1])

定义三维张量：

In [8]:
a = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])

In [9]:
a

<tf.Tensor: id=6, shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])>

创建字符串：

In [10]:
a = tf.constant('i am a chinese.')
a

<tf.Tensor: id=8, shape=(), dtype=string, numpy=b'i am a chinese.'>

字符串操作：

In [11]:
tf.strings.upper(a)

<tf.Tensor: id=10, shape=(), dtype=string, numpy=b'I AM A CHINESE.'>

布尔类型：

In [12]:
a = tf.constant(True)
a

<tf.Tensor: id=12, shape=(), dtype=bool, numpy=True>

布尔向量：

In [13]:
a = tf.constant([True, False])
a

<tf.Tensor: id=14, shape=(2,), dtype=bool, numpy=array([ True, False])>

数值精度：

In [14]:
tf.constant(123456789, dtype=tf.int16)

<tf.Tensor: id=16, shape=(), dtype=int16, numpy=-13035>

In [15]:
tf.constant(123456789, dtype=tf.int32)

<tf.Tensor: id=18, shape=(), dtype=int32, numpy=123456789>

PI的精度：

In [16]:
import numpy as np

np.pi

3.141592653589793

In [17]:
tf.constant(np.pi, dtype=tf.float32)

<tf.Tensor: id=20, shape=(), dtype=float32, numpy=3.1415927>

In [18]:
tf.constant(np.pi, dtype=tf.float64)

<tf.Tensor: id=22, shape=(), dtype=float64, numpy=3.141592653589793>

类型转换：

In [19]:
a = tf.constant(np.pi, dtype=tf.float16)
a

<tf.Tensor: id=24, shape=(), dtype=float16, numpy=3.14>

In [20]:
tf.cast(a, tf.float32)

<tf.Tensor: id=26, shape=(), dtype=float32, numpy=3.140625>

布尔类型和整数类型的转换：

In [21]:
a = tf.constant([True, False])
tf.cast(a, tf.int8)

<tf.Tensor: id=29, shape=(2,), dtype=int8, numpy=array([1, 0], dtype=int8)>

非0数字都是True:

In [22]:
tf.cast([1, 2, -1 , 0], tf.bool)

<tf.Tensor: id=32, shape=(4,), dtype=bool, numpy=array([ True,  True,  True, False])>

待优化张量：

In [23]:
a = tf.constant([1,2,3,4])
aa = tf.Variable(a)
aa.name, aa.trainable

('Variable:0', True)

2. 创建张量。

从numpy array中创建：

In [24]:
tf.convert_to_tensor(np.array([[1,2], [3.,4]]))

<tf.Tensor: id=42, shape=(2, 2), dtype=float64, numpy=
array([[1., 2.],
       [3., 4.]])>

创建全0，1标量：

In [25]:
tf.zeros([]),tf.ones([])

(<tf.Tensor: id=44, shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: id=45, shape=(), dtype=float32, numpy=1.0>)

创建全0，1向量：

In [26]:
tf.zeros([2]),tf.ones([3])

(<tf.Tensor: id=50, shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Tensor: id=53, shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>)

创建全0，1矩阵：

In [27]:
tf.zeros([2,3]),tf.ones([3,3])

(<tf.Tensor: id=58, shape=(2, 3), dtype=float32, numpy=
 array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: id=61, shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>)

创建和某个张量shape一致的全0，1张量：

In [28]:
tf.zeros_like(a)

<tf.Tensor: id=64, shape=(4,), dtype=int32, numpy=array([0, 0, 0, 0])>

创建自定义数值的张量：

In [29]:
tf.fill(tf.shape(a), -1)

<tf.Tensor: id=68, shape=(4,), dtype=int32, numpy=array([-1, -1, -1, -1])>

In [30]:
tf.fill([], -2)

<tf.Tensor: id=72, shape=(), dtype=int32, numpy=-2>

In [31]:
tf.fill([2,2], -1)

<tf.Tensor: id=76, shape=(2, 2), dtype=int32, numpy=
array([[-1, -1],
       [-1, -1]])>

创建正太分布的张量：

In [32]:
tf.random.normal([3,3], mean=0, stddev=1)

<tf.Tensor: id=83, shape=(3, 3), dtype=float32, numpy=
array([[-2.0249934 , -0.3333491 , -2.7344513 ],
       [-0.75663704, -0.16990145,  0.76856077],
       [ 0.35646287,  1.6815854 ,  0.0954161 ]], dtype=float32)>

创建均匀分布的张量：

In [33]:
tf.random.uniform([2,2], minval=0, maxval=1, dtype=tf.float32)

<tf.Tensor: id=91, shape=(2, 2), dtype=float32, numpy=
array([[0.2696942 , 0.05701089],
       [0.26538098, 0.08357155]], dtype=float32)>

创建序列;

In [34]:
tf.range(10)

<tf.Tensor: id=96, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [35]:
tf.range(0, 10, delta=1)

<tf.Tensor: id=101, shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

3.张量的典型应用。

矩阵也是非常常见的张量类型，比如全连接层的批量输入𝑋 = [𝑏, $𝑑_{𝑖𝑛}$ ]，其中𝑏表示输入
样本的个数，即batch size，$𝑑_{𝑖𝑛}$表示输入特征的长度。比如特征长度为4，一共包含2 个样
本的输入可以表示为矩阵：

In [36]:
x = tf.random.normal([2, 4])

假设输入有3个节点，则w表示为:

In [37]:
w = tf.ones([4, 3])

b表示为：

In [38]:
b = tf.zeros([3])

In [39]:
o = x@w + b
o

<tf.Tensor: id=116, shape=(2, 3), dtype=float32, numpy=
array([[-2.2087054 , -2.2087054 , -2.2087054 ],
       [ 0.45700884,  0.45700884,  0.45700884]], dtype=float32)>

图片的处理，例如4张32*32的彩色图片：

In [40]:
x = tf.random.normal([4, 32, 32, 3])
layer = layers.Conv2D(16, kernel_size=3)
out = layer(x)
out.shape

TensorShape([4, 30, 30, 16])

可以访问卷积核张量：

In [41]:
layer.kernel.shape

TensorShape([3, 3, 3, 16])

4.张量的索引和切片。

In [42]:
x = tf.random.normal([4, 32, 32, 3])

取第一张图片数据：

In [43]:
x[0]

<tf.Tensor: id=161, shape=(32, 32, 3), dtype=float32, numpy=
array([[[ 0.09448941, -0.07198378,  0.3972607 ],
        [-0.881061  , -0.5349489 ,  0.6665005 ],
        [-0.9721283 , -2.630834  , -0.11351258],
        ...,
        [ 1.6612664 ,  0.4118362 , -0.21476318],
        [ 1.5897295 ,  0.32726958, -0.45773008],
        [ 1.7548053 , -0.19228351,  1.9320621 ]],

       [[-1.8597443 , -1.0506842 ,  0.20765679],
        [-1.0137815 ,  0.88383424,  0.3740964 ],
        [-1.542704  , -0.7860946 ,  0.22205907],
        ...,
        [-1.0571097 ,  0.38986793,  1.1456537 ],
        [ 0.14960378, -1.0282735 , -0.36515057],
        [ 0.3787227 , -1.1982152 , -0.3405726 ]],

       [[-0.8443849 , -0.24177913, -2.048773  ],
        [-0.32925543, -0.43694267, -0.4417162 ],
        [ 1.0812519 , -0.09232543, -1.1789254 ],
        ...,
        [-0.14665832,  0.7175042 , -0.19737975],
        [ 0.90199935, -0.03110392,  0.42211524],
        [-0.8859993 , -0.24452367, -0.14426196]],

       ...,


取第一张图片的第二行：

In [44]:
x[0][1]

<tf.Tensor: id=170, shape=(32, 3), dtype=float32, numpy=
array([[-1.8597443 , -1.0506842 ,  0.20765679],
       [-1.0137815 ,  0.88383424,  0.3740964 ],
       [-1.542704  , -0.7860946 ,  0.22205907],
       [-0.4911616 , -0.8200738 , -1.4751756 ],
       [ 0.20182317,  0.12023496,  0.36576235],
       [-0.15585935,  0.70501333, -0.1650768 ],
       [-0.6385383 ,  0.14929692, -0.35914293],
       [-0.202073  , -0.09118687,  0.70976377],
       [-0.3022434 , -0.159974  ,  0.7108591 ],
       [-0.7926795 ,  0.20133509,  0.05820744],
       [ 0.4347381 , -0.75582105,  0.94135654],
       [ 1.5125794 ,  1.3149359 , -0.36251894],
       [-0.39134675,  0.20305203, -0.5931936 ],
       [-1.8405795 ,  1.2775186 ,  1.1569258 ],
       [-0.46200997,  0.6989832 ,  0.6044338 ],
       [-1.3954263 , -0.69763917, -0.4060376 ],
       [-0.42573   ,  1.5375113 ,  0.53119236],
       [ 1.1542703 ,  0.03604562,  0.22716703],
       [-1.0695527 , -0.85941714,  2.3088007 ],
       [ 2.5183663 ,  0.2017852

取第一张图片的第二行，第四列的像素：

In [45]:
x[0][1][3]

<tf.Tensor: id=183, shape=(3,), dtype=float32, numpy=array([-0.4911616, -0.8200738, -1.4751756], dtype=float32)>

取第一张图片的第二行，第四列的像素的B通道值：

In [46]:
x[0][1][3][2]

<tf.Tensor: id=200, shape=(), dtype=float32, numpy=-1.4751756>

也可以这样写：

In [47]:
x[0,1,3,2]

<tf.Tensor: id=205, shape=(), dtype=float32, numpy=-1.4751756>

第二个样本隔行隔列采样：

In [48]:
x[1, 0:28:2, 0:28:2,:]

<tf.Tensor: id=210, shape=(14, 14, 3), dtype=float32, numpy=
array([[[ 0.73401654, -1.2058098 , -0.5221599 ],
        [ 0.08795831, -0.39415658,  1.5225447 ],
        [-0.5425426 ,  0.54277736,  0.2632363 ],
        [-0.29333863, -0.33964312, -1.6562107 ],
        [ 0.49850878,  0.75241816,  0.01324889],
        [ 1.2416129 , -0.55015546, -0.26181814],
        [-0.38838902,  0.0732642 ,  0.48705658],
        [ 0.08408777, -0.7319648 ,  0.41697916],
        [ 0.33777183,  0.32103515, -0.23179603],
        [-1.9895552 , -0.1932585 , -1.7176075 ],
        [ 0.77944005,  0.21368891, -1.0395972 ],
        [ 0.4534441 , -0.0097742 ,  0.55667764],
        [-0.33639917,  0.59099436,  2.9079356 ],
        [-0.1502137 , -0.46802855, -1.4732088 ]],

       [[-0.2292678 , -1.3442638 ,  0.55780834],
        [-0.5668638 , -0.15558267,  0.2628339 ],
        [-0.16742676, -0.08834255, -1.1184311 ],
        [ 0.3500412 ,  0.28145352, -0.56560695],
        [ 0.14007543,  1.9112685 ,  1.801863  ],
      

相当于在图片的高宽各缩放至原来的50%。

step可以为负数:

In [49]:
x = tf.range(9)
x

<tf.Tensor: id=215, shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [50]:
x[8:0:-1]

<tf.Tensor: id=220, shape=(8,), dtype=int32, numpy=array([8, 7, 6, 5, 4, 3, 2, 1])>

In [51]:
x[8:0:1]

<tf.Tensor: id=225, shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

逆序间隔采样：

In [52]:
x[::-2]

<tf.Tensor: id=230, shape=(5,), dtype=int32, numpy=array([8, 6, 4, 2, 0])>

当维数过多，可以用...，例如读取第1,2张图片的G,B通道值：

In [53]:
x = tf.random.normal([4,32,32,3])
x[0:2,...,1:]

<tf.Tensor: id=241, shape=(2, 32, 32, 2), dtype=float32, numpy=
array([[[[-8.3739078e-01, -9.0266508e-01],
         [ 2.2082706e-01,  4.2596883e-01],
         [ 3.1196231e-01,  9.3580496e-01],
         ...,
         [-1.2356512e-01, -1.4185637e+00],
         [ 9.6177471e-01,  8.5953772e-02],
         [-6.9855797e-01, -2.3623338e-02]],

        [[-4.0964100e-01,  2.1698213e+00],
         [ 1.3123107e+00,  5.7625491e-02],
         [-8.2495779e-01,  6.8798256e-01],
         ...,
         [ 3.9232105e-01, -2.5460920e+00],
         [-4.2220220e-01,  1.2378458e-01],
         [ 1.4766570e+00, -9.6481472e-01]],

        [[-1.8557934e+00, -1.3910984e+00],
         [-4.6415305e-01, -2.7092078e-01],
         [-1.0094086e+00,  8.0301523e-01],
         ...,
         [-5.3441072e-01, -3.1323653e-01],
         [-1.7374965e+00,  2.3389568e-03],
         [-5.7772070e-01, -2.3453806e-01]],

        ...,

        [[ 6.5552735e-01, -1.0250862e+00],
         [-5.1775926e-01,  1.9002439e+00],
         [ 5.7

5.纬度变换。

改变视图:

In [54]:
x = tf.range(96)
x.shape

TensorShape([96])

In [55]:
b = tf.reshape(x, [2, 4, 4, 3])
b

<tf.Tensor: id=248, shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]])>

新增纬度：

In [56]:
x = tf.random.uniform([2, 28], maxval=10, dtype=tf.int32)
x

<tf.Tensor: id=253, shape=(2, 28), dtype=int32, numpy=
array([[9, 7, 1, 1, 2, 7, 1, 3, 6, 9, 5, 0, 2, 9, 0, 2, 7, 1, 3, 1, 0, 3,
        9, 4, 7, 1, 8, 4],
       [4, 8, 2, 5, 6, 6, 1, 6, 9, 1, 0, 7, 0, 0, 3, 8, 5, 9, 2, 6, 2, 9,
        5, 0, 4, 8, 4, 0]])>

In [57]:
y = tf.expand_dims(x, axis=0)
y

<tf.Tensor: id=256, shape=(1, 2, 28), dtype=int32, numpy=
array([[[9, 7, 1, 1, 2, 7, 1, 3, 6, 9, 5, 0, 2, 9, 0, 2, 7, 1, 3, 1, 0,
         3, 9, 4, 7, 1, 8, 4],
        [4, 8, 2, 5, 6, 6, 1, 6, 9, 1, 0, 7, 0, 0, 3, 8, 5, 9, 2, 6, 2,
         9, 5, 0, 4, 8, 4, 0]]])>

删除维度：

In [58]:
y = tf.squeeze(y, axis=0)
y

<tf.Tensor: id=258, shape=(2, 28), dtype=int32, numpy=
array([[9, 7, 1, 1, 2, 7, 1, 3, 6, 9, 5, 0, 2, 9, 0, 2, 7, 1, 3, 1, 0, 3,
        9, 4, 7, 1, 8, 4],
       [4, 8, 2, 5, 6, 6, 1, 6, 9, 1, 0, 7, 0, 0, 3, 8, 5, 9, 2, 6, 2, 9,
        5, 0, 4, 8, 4, 0]])>

交换维度：

In [59]:
x = tf.random.normal([2, 4, 4, 3])
x

<tf.Tensor: id=265, shape=(2, 4, 4, 3), dtype=float32, numpy=
array([[[[ 0.49437642,  0.45573685, -0.20116872],
         [-0.07239521,  1.1448351 , -1.8645545 ],
         [ 0.14517088,  1.8629376 ,  1.949122  ],
         [-0.74515516, -0.63690823, -0.25047708]],

        [[-0.00982935,  0.91370445,  0.08548588],
         [-0.5439232 , -0.11996564,  1.2472528 ],
         [-1.8104815 ,  0.24239427, -0.47999576],
         [-2.9315698 ,  2.5705469 , -0.2939242 ]],

        [[-1.061615  ,  0.9709544 ,  1.6522598 ],
         [-0.06250096, -0.5002315 ,  0.0907607 ],
         [ 0.51200706, -0.40487355,  0.01813413],
         [-0.49111587,  0.2654742 , -0.30879784]],

        [[ 1.0949973 , -1.0338459 ,  0.57658786],
         [ 1.3494128 ,  0.08951985,  1.0573262 ],
         [ 1.2270001 , -0.4001184 , -0.30121142],
         [-1.7238938 , -1.9484409 , -1.500688  ]]],


       [[[ 0.03187727,  1.3926213 , -1.5160444 ],
         [-0.9898932 ,  0.2895146 , -1.5949177 ],
         [-1.0791664 , -0.68

In [60]:
y = tf.transpose(x, perm=[0,3,1,2])
y

<tf.Tensor: id=268, shape=(2, 3, 4, 4), dtype=float32, numpy=
array([[[[ 0.49437642, -0.07239521,  0.14517088, -0.74515516],
         [-0.00982935, -0.5439232 , -1.8104815 , -2.9315698 ],
         [-1.061615  , -0.06250096,  0.51200706, -0.49111587],
         [ 1.0949973 ,  1.3494128 ,  1.2270001 , -1.7238938 ]],

        [[ 0.45573685,  1.1448351 ,  1.8629376 , -0.63690823],
         [ 0.91370445, -0.11996564,  0.24239427,  2.5705469 ],
         [ 0.9709544 , -0.5002315 , -0.40487355,  0.2654742 ],
         [-1.0338459 ,  0.08951985, -0.4001184 , -1.9484409 ]],

        [[-0.20116872, -1.8645545 ,  1.949122  , -0.25047708],
         [ 0.08548588,  1.2472528 , -0.47999576, -0.2939242 ],
         [ 1.6522598 ,  0.0907607 ,  0.01813413, -0.30879784],
         [ 0.57658786,  1.0573262 , -0.30121142, -1.500688  ]]],


       [[[ 0.03187727, -0.9898932 , -1.0791664 , -0.20351705],
         [ 0.03835795,  1.2204373 , -2.302266  , -0.11076134],
         [ 1.3009849 ,  0.88943195,  0.69834   ,

数据复制:

In [63]:
b = tf.constant([1,2])
b = tf.expand_dims(b, axis=0)
b

<tf.Tensor: id=794, shape=(1, 2), dtype=int32, numpy=array([[1, 2]])>

In [65]:
b = tf.tile(b, multiples=[2,1])
b

<tf.Tensor: id=800, shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])>

广播机制：

In [68]:
x = tf.random.normal([2,4])
w = tf.ones([4,3])
b = tf.zeros([3])
y = x@w + b
y

<tf.Tensor: id=843, shape=(2, 3), dtype=float32, numpy=
array([[1.5603006 , 1.5603006 , 1.5603006 ],
       [0.97769535, 0.97769535, 0.97769535]], dtype=float32)>

上述代码自动推导，自动调用tf.broadcast_to完成计算，等价于：

In [70]:
y = x@w + tf.broadcast_to(b, [2,3])

显示的shape扩张：

In [72]:
a = tf.random.normal([32, 1])
a = tf.broadcast_to(a, [2, 32, 32, 3])

In [75]:
a.shape

TensorShape([2, 32, 32, 3])

In [76]:
a = tf.random.normal([2, 32, 32, 1])
b = tf.random.normal([32, 32])
a+b,a-b,a*b,a/b

(<tf.Tensor: id=2046, shape=(2, 32, 32, 32), dtype=float32, numpy=
 array([[[[-1.7647635e+00, -1.4102317e-01,  1.9089935e+00, ...,
           -6.1659324e-01, -4.6839893e-01,  1.2279582e+00],
          [-1.7012602e-01, -8.7247211e-01, -1.8547388e+00, ...,
           -4.9077770e-01, -8.2729226e-01,  8.8393724e-01],
          [ 1.1359652e+00,  2.2716200e-01,  7.5811172e-01, ...,
            1.5490886e+00,  5.2278996e-02,  2.2052169e-01],
          ...,
          [ 7.3501647e-02,  6.4287388e-01,  3.0143857e-02, ...,
            7.0586276e-01,  6.8687940e-01,  1.9253534e-01],
          [ 4.9191117e-03,  9.9384457e-01, -4.7118670e-01, ...,
           -5.1199967e-01, -2.4826574e-01, -1.2759218e-01],
          [-2.3307600e+00, -1.1448890e+00, -8.9740872e-02, ...,
            5.6085813e-01, -1.0130892e+00, -2.1156027e+00]],
 
         [[-1.5653455e+00,  5.8394730e-02,  2.1084113e+00, ...,
           -4.1717535e-01, -2.6898104e-01,  1.4273760e+00],
          [ 1.6990737e+00,  9.9672759e-01,  1.4

可以看到，自动推导按照最右优先原则。

5.数学运算。

加减乘除是最基本的数学运算，分别通过tf.add, tf.subtract, tf.multiply, tf.divide 函数实
现，TensorFlow 已经重载了+ −∗/运算符，一般推荐直接使用运算符来完成加减乘除运
算。

整除和余除也是常见的运算之一，分别通过//和%运算符实现，如下所示：

In [78]:
a = tf.range(5)
b = tf.constant(2)
a//2

<tf.Tensor: id=2712, shape=(5,), dtype=int32, numpy=array([0, 0, 1, 1, 2])>

In [79]:
a%2

<tf.Tensor: id=3383, shape=(5,), dtype=int32, numpy=array([0, 1, 0, 1, 0])>

乘方：

In [80]:
x = tf.range(5)
tf.pow(x, 2)

<tf.Tensor: id=3390, shape=(5,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16])>

根号运算：

In [85]:
x = tf.constant([1., 2., 3.])
x**0.5

<tf.Tensor: id=3409, shape=(3,), dtype=float32, numpy=array([1.       , 1.4142135, 1.7320508], dtype=float32)>

平方和平方根：

In [89]:
x = tf.range(5)
tf.square(x)

<tf.Tensor: id=3424, shape=(5,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16])>

In [90]:
x = tf.cast(x, dtype=tf.float32)
tf.sqrt(x)

<tf.Tensor: id=3427, shape=(5,), dtype=float32, numpy=
array([0.       , 1.       , 1.4142135, 1.7320508, 2.       ],
      dtype=float32)>

指数和对数：