概要：

In [2]:
import tensorflow as tf
from    tensorflow import keras
from    tensorflow.keras import layers, optimizers, datasets

1.合并和分割。

拼接：

In [4]:
a = tf.random.normal([4, 35, 8])
b = tf.random.normal([6, 35, 8])
c = tf.concat([a,b], axis=0)
c.shape

TensorShape([10, 35, 8])

In [6]:
a = tf.random.normal([4, 35, 4])
b = tf.random.normal([4, 35, 5])
c = tf.concat([a,b], axis=2)
c.shape

TensorShape([4, 35, 9])

In [9]:
a = tf.random.normal([35, 5])
b = tf.random.normal([35, 5])
c = tf.stack([a,b], axis=0)
c.shape

TensorShape([2, 35, 5])

分割：

In [12]:
a = tf.random.normal([10, 35, 8])
b = tf.split(a, axis=0, num_or_size_splits=10)
len(b)

10

In [14]:
b[0].shape

TensorShape([1, 35, 8])

不等长分割：

In [17]:
b = tf.split(a, axis=0, num_or_size_splits=[4,2,2,2])
len(b)

4

In [18]:
b[0].shape

TensorShape([4, 35, 8])

2.范数。

In [ ]:
向量L1范数：所有元素的绝对值之和。
向量L2范数：所有元素的平方和，然后开根号。
向量∞范数：所有元素的绝对值的最大值。

In [19]:
x = tf.ones([3,3])
tf.norm(x, ord=1)

<tf.Tensor: id=301, shape=(), dtype=float32, numpy=9.0>

In [20]:
tf.norm(x, ord=2)

<tf.Tensor: id=307, shape=(), dtype=float32, numpy=3.0>

In [22]:
import numpy as np
tf.norm(x, ord=np.inf)

<tf.Tensor: id=312, shape=(), dtype=float32, numpy=1.0>

3.最大值，最小值，均值，和。

最大值：

In [23]:
x = tf.random.normal([4,10])
tf.reduce_max(x, axis=1)

<tf.Tensor: id=321, shape=(4,), dtype=float32, numpy=array([2.564948  , 1.4235917 , 0.94367754, 1.3990991 ], dtype=float32)>

最小值：

In [25]:
tf.reduce_min(x, axis=1)

<tf.Tensor: id=324, shape=(4,), dtype=float32, numpy=array([-0.6842463, -2.2944338, -1.3083159, -1.5104798], dtype=float32)>

均值：

In [26]:
tf.reduce_mean(x, axis=1)

<tf.Tensor: id=327, shape=(4,), dtype=float32, numpy=array([ 0.7458538 , -0.07444952, -0.20139094,  0.02124277], dtype=float32)>

和：

In [27]:
tf.reduce_sum(x, axis=1)

<tf.Tensor: id=330, shape=(4,), dtype=float32, numpy=array([ 7.458538  , -0.7444953 , -2.0139093 ,  0.21242774], dtype=float32)>

最大值的索引:

In [32]:
out = tf.random.normal([2, 3])
out

<tf.Tensor: id=478, shape=(2, 3), dtype=float32, numpy=
array([[-0.61119163, -0.6519431 , -0.8915881 ],
       [ 0.5899282 , -1.3094941 ,  1.4833547 ]], dtype=float32)>

In [33]:
out = tf.nn.softmax(out, axis=1)
out

<tf.Tensor: id=480, shape=(2, 3), dtype=float32, numpy=
array([[0.36824927, 0.35354424, 0.2782065 ],
       [0.27830788, 0.04165018, 0.6800419 ]], dtype=float32)>

张量比较：

In [35]:
out = tf.random.normal([100, 10])
out = tf.nn.softmax(out, axis=1)
pred = tf.argmax(out, axis=1)
pred

<tf.Tensor: id=499, shape=(100,), dtype=int64, numpy=
array([1, 2, 3, 2, 8, 7, 0, 1, 1, 5, 3, 7, 6, 6, 6, 0, 5, 9, 5, 0, 9, 6,
       9, 4, 3, 1, 4, 4, 6, 3, 6, 9, 3, 8, 6, 0, 3, 9, 9, 8, 2, 4, 7, 8,
       3, 0, 7, 1, 7, 4, 2, 8, 9, 1, 9, 4, 4, 0, 3, 2, 8, 0, 2, 8, 6, 7,
       7, 0, 6, 9, 3, 2, 0, 6, 7, 8, 8, 3, 3, 7, 8, 4, 2, 5, 0, 7, 1, 5,
       1, 9, 3, 7, 2, 4, 9, 2, 2, 8, 4, 1], dtype=int64)>

In [39]:
y = tf.random.uniform([100], maxval=10, dtype=tf.int64)
p = tf.equal(pred, y)

In [41]:
p = tf.cast(p, dtype=tf.float32)
p.shape

TensorShape([100])

In [42]:
tf.reduce_sum(p)

<tf.Tensor: id=519, shape=(), dtype=float32, numpy=11.0>

4.填充和复制。

填充:

In [44]:
a = tf.constant([1,2,3,4,5,6])
b = tf.constant([3,4,2,1])
tf.pad(b, [[0,2]])

<tf.Tensor: id=550, shape=(6,), dtype=int32, numpy=array([3, 4, 2, 1, 0, 0])>

复制：

In [48]:
x = tf.random.normal([2,3,4])
x = tf.tile(x, multiples=[2,2,1]) 
x.shape

TensorShape([4, 6, 4])

5.数据限幅。

In [52]:
x = tf.range(9)
tf.maximum(x, 2)

<tf.Tensor: id=605, shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 8])>

In [54]:
tf.minimum(x, 7)

<tf.Tensor: id=608, shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 7])>

In [55]:
tf.clip_by_value(x, 2, 7)

<tf.Tensor: id=613, shape=(9,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5, 6, 7, 7])>